ARG stage

FROM node:24 AS builder

ARG stage

WORKDIR /app

COPY package*.json ./
RUN npm ci
COPY . .

RUN REACT_APP_STAGE=${stage} npm run build;

FROM nginx:1.25-alpine

ARG stage

COPY --from=builder /app/build /usr/share/nginx/html

COPY nginx/nginx-${stage}.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]