# General System/Spring values
server.address=0.0.0.0
server.port=80
server.max-http-header-size=32KB
# Application values
spring.application.name=QuantumVestiges
mybatis.mapper-locations=classpath:com/gamerparadise/dao/mapper/*.xml
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-west-2.amazonaws.com/us-west-2_A9tCE18yj
cors.allowed.origins=https://devo.quantumvestiges.com,https://localhost:3000

cognito.user_pool_id=us-west-2_A9tCE18yj
s3.bucket.name.games=games-devo
rds.secret=QuantumVestiges-devo