# General System/Spring values
server.address=0.0.0.0
server.port=80
server.max-http-header-size=32KB
# Application values
spring.application.name=QuantumVestiges
mybatis.mapper-locations=classpath:com/gamerparadise/dao/mapper/*.xml
cors.allowed.origins=https://prod.quantumvestiges.com,https://www.quantumvestiges.com,https://quantumvestiges.com

cognito.user_pool_id=us-west-2
s3.bucket.name.games=games-prod
rds.secret=QuantumVestiges-prod